FROM tensorflow/tensorflow:1.6.0-py3

MAINTAINER Seongheon Henry Lee <skynspace@kaist.ac.kr>
#docker run -d -p 8888:8888 -p 6006:6006 -v $PWD:/mnt/notebooks/ 

RUN apt-get update

#! Linux apps. 
RUN apt-get install -y \
        build-essential \
        cmake \
        git \
        libavformat-dev \
        libhdf5-dev \
        libjasper-dev \
        libjpeg-dev \
        libpng-dev \
        libpq-dev \
        libswscale-dev \
        libtbb-dev \
        libtbb2 \
        libtiff-dev \
        pkg-config \
        python-opengl \
        unzip \
        vim \
        wget \
        yasm
        
        
#! Python libs. 
RUN pip3 --no-cache-dir install \
        h5py \
        hdf5storage \
        numpy \
        py3nvml \
        scipy
        
# OpenAI Gym
RUN pip3 --no-cache-dir install \
        gym
        
# DependencY to render OpenAI Gym in a Jupyter notebook as a gif.
WORKDIR /tmp
RUN git clone https://github.com/jakevdp/JSAnimation \
        && cd JSAnimation \
        && python3 setup.py install


#! Jupyter Notebook
EXPOSE 8888


#! TensorBoard
EXPOSE 6006


WORKDIR /mnt/notebooks